import type { Metadata } from "next";
import { Cairo, Kavoon, Leckerli_One } from "next/font/google";
import "./globals.css";

// Base Font
const cairo = Cairo({
  subsets: ["latin"],
  weight: "400",
  variable: "--base-font",
  display: "swap",
});
// Special Font
const leckerliOne = Leckerli_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--special-font",
  display: "swap",
});
// The Font Used In Brand
const kavoon = Kavoon({
  subsets: ["latin"],
  weight: "400",
  variable: "--icon-font",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cairo.variable} ${leckerliOne.variable} ${kavoon.variable} font-base`}
      >
        {children}
      </body>
    </html>
  );
}
