import { RealProduct } from "@/lib/types/products";

export const products: RealProduct[] = [
  {
    id: "001",
    name_ar: "أحذية أكسفورد كلاسيكية للرجال",
    name_en: "Men's Classic Oxford Shoes",
    img: "/products/product-001.webp",
    description_ar:
      "أحذية أكسفورد كلاسيكية للرجال، مثالية للمناسبات الرسمية.\nمصنوعة من جلد طبيعي ونعل متين.",
    description_en:
      "Classic Oxford shoes for men, perfect for formal occasions.\nMade with genuine leather and durable sole.",
    categories: ["FORMAL_SHOES", "MENS_SHOES"],
    colors: ["BLACK", "BROWN", "BLUE"],
    price: { original: "89.99", sale: null },
    relatedProducts: ["002", "003", "004", "005"],
    rating: 4,
    inStock: 76,
  },
  {
    id: "002",
    name_ar: "حذاء رياضي كاجوال للنساء",
    name_en: "Women's Casual Sneakers",
    img: "/products/product-002.webp",
    description_ar:
      "حذاء رياضي مريح وأنيق للنساء.\nمثالي للنزهات العادية والارتداء اليومي.",
    description_en:
      "Comfortable and stylish sneakers for women.\nPerfect for casual outings and daily wear.",
    categories: ["SNEAKERS", "WOMENS_SHOES"],
    colors: ["WHITE", "GREY", "PINK"],
    price: { original: "69.99", sale: "49.99" },
    relatedProducts: ["001", "006", "007", "008"],
    rating: 5,
    inStock: 2,
  },
  {
    id: "003",
    name_ar: "حذاء داخلي من جلد الغزال للرجال",
    name_en: "Men's Leather Loafers",
    img: "/products/product-003.webp",
    description_ar:
      "حذاء داخلي من جلد الغزال الكلاسيكي للرجال، مناسب للارتداء العادي والرسمي على حد سواء.\nناعم ومريح بتصميم سهل الارتداء.",
    description_en:
      "Classic leather loafers for men, suitable for both casual and formal wear.\nSoft and comfortable with a slip-on design.",
    categories: ["LOAFERS", "MENS_SHOES"],
    colors: ["BROWN", "BLACK"],
    price: { original: "79.99", sale: null },
    relatedProducts: ["001", "004", "009", "010"],
    rating: 4,
    inStock: 28,
  },
  {
    id: "004",
    name_ar: "حذاء كعب عالي للنساء",
    name_en: "Women's High Heel Pumps",
    img: "/products/product-004.webp",
    description_ar:
      "حذاء كعب عالي أنيق للنساء، مثالي للمناسبات الرسمية.\nمصنوع من مواد عالية الجودة للمتانة والأناقة.",
    description_en:
      "Elegant high heel pumps for women, perfect for formal events.\nMade with premium materials for durability and style.",
    categories: ["HEELS", "WOMENS_SHOES"],
    colors: ["BLACK", "RED"],
    price: { original: "99.99", sale: null },
    relatedProducts: ["001", "003", "011", "012"],
    rating: 3,
    inStock: 48,
  },
  {
    id: "005",
    name_ar: "أحذية ركض رياضية للرجال",
    name_en: "Men's Athletic Running Shoes",
    img: "/products/product-005.webp",
    description_ar:
      "أحذية ركض خفيفة الوزن ومنسوجة للرجال.\nمصممة لتحقيق أفضل أداء وراحة.",
    description_en:
      "Lightweight and breathable running shoes for men.\nDesigned for optimal performance and comfort.",
    categories: ["ATHLETIC_SHOES", "MENS_SHOES"],
    colors: ["BLUE", "BLACK", "GREY"],
    price: { original: "79.99", sale: null },
    relatedProducts: ["001", "013", "014", "015"],
    rating: 4,
    inStock: 50,
  },
  {
    id: "006",
    name_ar: "أحذية كاحل للنساء",
    name_en: "Women's Ankle Boots",
    img: "/products/product-006.webp",
    description_ar:
      "أحذية كاحل أنيقة للنساء، مثالية لفصلي الخريف والشتاء.\nمصنوعة من جلد صناعي وكعب متين.",
    description_en:
      "Stylish ankle boots for women, perfect for fall and winter.\nMade with faux leather and a sturdy heel.",
    categories: ["BOOTS", "WOMENS_SHOES"],
    colors: ["BROWN", "BLACK", "TAUPE"],
    price: { original: "59.99", sale: "39.99" },
    relatedProducts: ["002", "016", "017", "018"],
    rating: 5,
    inStock: 4,
  },
  {
    id: "007",
    name_ar: "أحذية شيلسي سويد للرجال",
    name_en: "Men's Suede Chelsea Boots",
    img: "/products/product-007.webp",
    description_ar:
      "أحذية شيلسي سويد رائجة للرجال، مناسبة لأي مناسبة.\nلوحات جانبية مرنة لسهولة الانزلاق والخروج.",
    description_en:
      "Trendy suede Chelsea boots for men, suitable for any occasion.\nElastic side panels for easy slip-on and off.",
    categories: ["BOOTS", "MENS_SHOES"],
    colors: ["TAN", "BLACK", "NAVY"],
    price: { original: "89.99", sale: null },
    relatedProducts: ["002", "019", "020", "021"],
    rating: 5,
    inStock: 78,
  },
  {
    id: "008",
    name_ar: "شقق باليه للنساء",
    name_en: "Women's Ballet Flats",
    img: "/products/product-008.webp",
    description_ar:
      "شقق باليه كلاسيكية للنساء، متعددة الاستخدامات ومريحة.\nمتوفرة بألوان مختلفة لتتناسب مع أي ملابس.",
    description_en:
      "Classic ballet flats for women, versatile and comfortable.\nAvailable in various colors to match any outfit.",
    categories: ["FLATS", "WOMENS_SHOES"],
    colors: ["BLACK", "BEIGE", "NAVY"],
    price: { original: "49.99", sale: null },
    relatedProducts: ["002", "022", "023", "024"],
    rating: 4,
    inStock: 57,
  },
  {
    id: "009",
    name_ar: "حذاء رياضي منزلق للرجال",
    name_en: "Men's Slip-On Sneakers",
    img: "/products/product-009.webp",
    description_ar:
      "حذاء رياضي منزلق عادي للرجال، سهل الارتداء وأنيق.\nتصميم خفيف الوزن مع وسادة داخلية مبطنة.",
    description_en:
      "Casual slip-on sneakers for men, easy to wear and stylish.\nLightweight construction with a cushioned insole.",
    categories: ["SNEAKERS", "MENS_SHOES"],
    colors: ["WHITE", "BLACK", "GREY"],
    price: { original: "59.99", sale: null },
    relatedProducts: ["003", "025", "026", "027"],
    rating: 3,
    inStock: 34,
  },
  {
    id: "010",
    name_ar: "صندل نسائي بكعب عالي",
    name_en: "Women's High Heel Sandals",
    img: "/products/product-010.webp",
    description_ar:
      "صندل نسائي بكعب عالي مثالي للمناسبات الصيفية.\nمصنوع من مواد مريحة ومتينة.",
    description_en:
      "Women's high heel sandals perfect for summer occasions.\nMade with comfortable and durable materials.",
    categories: ["SANDALS", "WOMENS_SHOES"],
    colors: ["BLACK", "GOLD", "SILVER"],
    price: { original: "79.99", sale: "59.99" },
    relatedProducts: ["004", "028", "029", "030"],
    rating: 4,
    inStock: 15,
  },
  {
    id: "011",
    name_ar: "أحذية رياضية مريحة للنساء",
    name_en: "Women's Comfortable Sneakers",
    img: "/products/product-011.webp",
    description_ar:
      "أحذية رياضية مريحة وأنيقة للنساء.\nتصميم يوفر دعمًا ممتازًا وراحة طوال اليوم.",
    description_en:
      "Comfortable and stylish sneakers for women.\nDesigned to provide excellent support and all-day comfort.",
    categories: ["SNEAKERS", "WOMENS_SHOES"],
    colors: ["BLACK", "WHITE", "GREY"],
    price: { original: "69.99", sale: null },
    relatedProducts: ["002", "031", "032", "033"],
    rating: 5,
    inStock: 63,
  },
  {
    id: "012",
    name_ar: "حذاء ركض خفيف للرجال",
    name_en: "Men's Lightweight Running Shoes",
    img: "/products/product-012.webp",
    description_ar:
      "حذاء ركض خفيف الوزن ومناسب للرجال.\nمصمم لتحقيق السرعة والراحة أثناء الجري.",
    description_en:
      "Lightweight and suitable running shoes for men.\nDesigned for speed and comfort during running.",
    categories: ["ATHLETIC_SHOES", "MENS_SHOES"],
    colors: ["BLACK", "RED", "BLUE"],
    price: { original: "89.99", sale: null },
    relatedProducts: ["001", "013", "034", "035"],
    rating: 4,
    inStock: 22,
  },
  {
    id: "013",
    name_ar: "حذاء رياضي مريح للنساء",
    name_en: "Women's Comfort Sports Shoes",
    img: "/products/product-013.webp",
    description_ar:
      "حذاء رياضي مريح للنساء، يوفر دعمًا ممتازًا للقدمين أثناء التمرينات الرياضية.\nمصنوع من مواد عالية الجودة.",
    description_en:
      "Comfortable sports shoes for women, providing excellent foot support during workouts.\nMade with high-quality materials.",
    categories: ["ATHLETIC_SHOES", "WOMENS_SHOES"],
    colors: ["WHITE", "GREY", "PINK"],
    price: { original: "79.99", sale: null },
    relatedProducts: ["002", "005", "036", "037"],
    rating: 5,
    inStock: 41,
  },
  {
    id: "014",
    name_ar: "أحذية ركض خفيفة للنساء",
    name_en: "Women's Lightweight Running Shoes",
    img: "/products/product-014.webp",
    description_ar:
      "أحذية ركض خفيفة للنساء، مثالية للركض اليومي والتمارين الرياضية.\nتصميم يوفر دعمًا وراحة طوال اليوم.",
    description_en:
      "Lightweight running shoes for women, perfect for daily running and sports activities.\nDesigned for support and comfort all day long.",
    categories: ["ATHLETIC_SHOES", "WOMENS_SHOES"],
    colors: ["BLUE", "PINK", "BLACK"],
    price: { original: "69.99", sale: null },
    relatedProducts: ["002", "005", "038", "039"],
    rating: 4,
    inStock: 56,
  },
  {
    id: "015",
    name_ar: "حذاء كاحل مريح للرجال",
    name_en: "Men's Comfortable Ankle Boots",
    img: "/products/product-015.webp",
    description_ar:
      "حذاء كاحل مريح للرجال، يوفر الراحة والأناقة في آن واحد.\nمثالي للملابس اليومية والمناسبات الرسمية.",
    description_en:
      "Comfortable ankle boots for men, providing comfort and style in one.\nIdeal for daily wear and formal occasions.",
    categories: ["BOOTS", "MENS_SHOES"],
    colors: ["BLACK", "BROWN", "TAN"],
    price: { original: "79.99", sale: "59.99" },
    relatedProducts: ["001", "003", "040", "041"],
    rating: 5,
    inStock: 9,
  },
  {
    id: "016",
    name_ar: "حذاء سهرة للنساء بكعب عالي",
    name_en: "Women's Evening High Heel Shoes",
    img: "/products/product-016.webp",
    description_ar:
      "حذاء سهرة أنيق للنساء بكعب عالي، مثالي للمناسبات الخاصة والأمسيات.\nمصمم بأناقة وتفاصيل رائعة.",
    description_en:
      "Stylish evening high heel shoes for women, perfect for special occasions and evenings.\nDesigned with elegance and exquisite details.",
    categories: ["HEELS", "WOMENS_SHOES"],
    colors: ["BLACK", "SILVER", "GOLD"],
    price: { original: "89.99", sale: null },
    relatedProducts: ["002", "004", "042", "043"],
    rating: 4,
    inStock: 37,
  },
  {
    id: "017",
    name_ar: "أحذية كاحل بدون كعب للنساء",
    name_en: "Women's Flat Ankle Boots",
    img: "/products/product-017.webp",
    description_ar:
      "أحذية كاحل بدون كعب للنساء، توفر الراحة والأناقة.\nمثالية للملابس اليومية خلال فصلي الخريف والشتاء.",
    description_en:
      "Flat ankle boots for women, providing comfort and style.\nPerfect for daily wear during fall and winter seasons.",
    categories: ["BOOTS", "WOMENS_SHOES"],
    colors: ["BROWN", "BLACK", "GREY"],
    price: { original: "49.99", sale: null },
    relatedProducts: ["002", "006", "044", "045"],
    rating: 5,
    inStock: 19,
  },
  {
    id: "018",
    name_ar: "صندل نسائي بسيط",
    name_en: "Women's Simple Sandals",
    img: "/products/product-018.webp",
    description_ar:
      "صندل نسائي بتصميم بسيط ومريح.\nمثالي للارتداء اليومي في فصل الصيف.",
    description_en:
      "Simple and comfortable women's sandals.\nPerfect for daily wear in the summer season.",
    categories: ["SANDALS", "WOMENS_SHOES"],
    colors: ["BLACK", "WHITE", "BROWN"],
    price: { original: "39.99", sale: null },
    relatedProducts: ["004", "010", "046", "047"],
    rating: 4,
    inStock: 62,
  },
  {
    id: "019",
    name_ar: "أحذية شتوية دافئة للرجال",
    name_en: "Men's Warm Winter Boots",
    img: "/products/product-019.webp",
    description_ar:
      "أحذية شتوية دافئة وأنيقة للرجال.\nمثالية للأيام الباردة والمناسبات الشتوية.",
    description_en:
      "Warm and stylish winter boots for men.\nPerfect for cold days and winter occasions.",
    categories: ["BOOTS", "MENS_SHOES"],
    colors: ["BLACK", "BROWN", "GREY"],
    price: { original: "109.99", sale: null },
    relatedProducts: ["001", "007", "048", "049"],
    rating: 5,
    inStock: 5,
  },
  {
    id: "020",
    name_ar: "حذاء ركض رياضي للنساء",
    name_en: "Women's Sports Running Shoes",
    img: "/products/product-020.webp",
    description_ar:
      "حذاء ركض رياضي للنساء، يوفر الراحة والأداء الأمثل.\nمثالي للتمارين الرياضية والجري اليومي.",
    description_en:
      "Women's sports running shoes, providing comfort and optimal performance.\nPerfect for sports workouts and daily running.",
    categories: ["ATHLETIC_SHOES", "WOMENS_SHOES"],
    colors: ["BLACK", "BLUE", "PINK"],
    price: { original: "79.99", sale: null },
    relatedProducts: ["002", "005", "021", "022"],
    rating: 4,
    inStock: 71,
  },
  {
    id: "021",
    name_ar: "حذاء بكعب عالي للنساء",
    name_en: "Women's High Heel Shoes",
    img: "/products/product-021.webp",
    description_ar:
      "حذاء نسائي بكعب عالي أنيق ومثالي للمناسبات الرسمية.\nمتوفر بألوان مختلفة.",
    description_en:
      "Stylish women's high heel shoes, perfect for formal occasions.\nAvailable in various colors.",
    categories: ["HEELS", "WOMENS_SHOES"],
    colors: ["BLACK", "RED", "SILVER"],
    price: { original: "99.99", sale: null },
    relatedProducts: ["004", "008", "023", "024"],
    rating: 5,
    inStock: 33,
  },
  {
    id: "022",
    name_ar: "شقق باليه للنساء بكعب منخفض",
    name_en: "Women's Low Heel Ballet Flats",
    img: "/products/product-022.webp",
    description_ar:
      "شقق باليه للنساء بكعب منخفض، مريحة وأنيقة.\nمثالية للارتداء اليومي.",
    description_en:
      "Women's low heel ballet flats, comfortable and stylish.\nPerfect for daily wear.",
    categories: ["FLATS", "WOMENS_SHOES"],
    colors: ["BLACK", "BEIGE", "NAVY"],
    price: { original: "59.99", sale: null },
    relatedProducts: ["002", "008", "025", "026"],
    rating: 4,
    inStock: 60,
  },
  {
    id: "023",
    name_ar: "أحذية بأحزمة للنساء",
    name_en: "Women's Strappy Sandals",
    img: "/products/product-023.webp",
    description_ar:
      "صندل نسائي بأحزمة عصري وأنيق، مثالي للصيف والمناسبات الخاصة.\nمتوفر بعدة ألوان.",
    description_en:
      "Stylish and elegant women's strappy sandals, perfect for summer and special occasions.\nAvailable in multiple colors.",
    categories: ["SANDALS", "WOMENS_SHOES"],
    colors: ["BLACK", "SILVER", "GOLD"],
    price: { original: "69.99", sale: null },
    relatedProducts: ["004", "010", "027", "028"],
    rating: 5,
    inStock: 18,
  },
  {
    id: "024",
    name_ar: "أحذية لوفرز للرجال",
    name_en: "Men's Classic Loafers",
    img: "/products/product-024.webp",
    description_ar:
      "أحذية لوفرز كلاسيكية للرجال، مثالية للارتداء اليومي والمناسبات الرسمية.\nمصنوعة من جلد طبيعي عالي الجودة.",
    description_en:
      "Classic loafers for men, perfect for daily wear and formal occasions.\nMade with high-quality genuine leather.",
    categories: ["LOAFERS", "MENS_SHOES"],
    colors: ["BROWN", "BLACK", "BLUE"],
    price: { original: "79.99", sale: null },
    relatedProducts: ["001", "003", "029", "030"],
    rating: 4,
    inStock: 25,
  },
  {
    id: "025",
    name_ar: "حذاء رياضي للرجال بكعب منخفض",
    name_en: "Men's Low Heel Athletic Shoes",
    img: "/products/product-025.webp",
    description_ar:
      "حذاء رياضي للرجال بكعب منخفض، يوفر الراحة والأداء الأمثل أثناء التمارين.\nمصمم بتقنيات حديثة لتحقيق أداء ممتاز.",
    description_en:
      "Men's low heel athletic shoes, providing comfort and optimal performance during workouts.\nDesigned with modern technologies for excellent performance.",
    categories: ["ATHLETIC_SHOES", "MENS_SHOES"],
    colors: ["BLACK", "BLUE", "GREY"],
    price: { original: "69.99", sale: null },
    relatedProducts: ["001", "005", "031", "032"],
    rating: 5,
    inStock: 53,
  },
  {
    id: "026",
    name_ar: "حذاء رياضي للنساء بكعب منخفض",
    name_en: "Women's Low Heel Sports Shoes",
    img: "/products/product-026.webp",
    description_ar:
      "حذاء رياضي للنساء بكعب منخفض، يوفر الراحة والأداء الأمثل أثناء التمارين.\nمصمم بتقنيات حديثة لتحقيق أداء ممتاز.",
    description_en:
      "Women's low heel sports shoes, providing comfort and optimal performance during workouts.\nDesigned with modern technologies for excellent performance.",
    categories: ["ATHLETIC_SHOES", "WOMENS_SHOES"],
    colors: ["BLACK", "WHITE", "PINK"],
    price: { original: "64.99", sale: null },
    relatedProducts: ["002", "005", "033", "034"],
    rating: 4,
    inStock: 44,
  },
  {
    id: "027",
    name_ar: "صندل نسائي مريح بدون كعب",
    name_en: "Women's Comfortable Flat Sandals",
    img: "/products/product-027.webp",
    description_ar:
      "صندل نسائي مريح بدون كعب، مثالي للارتداء اليومي خلال فصل الصيف.\nمتوفر بعدة ألوان.",
    description_en:
      "Comfortable flat sandals for women, perfect for daily wear during the summer season.\nAvailable in multiple colors.",
    categories: ["SANDALS", "WOMENS_SHOES"],
    colors: ["BLACK", "BROWN", "SILVER"],
    price: { original: "44.99", sale: null },
    relatedProducts: ["004", "010", "035", "036"],
    rating: 5,
    inStock: 28,
  },
  {
    id: "028",
    name_ar: "صندل نسائي بكعب متوسط",
    name_en: "Women's Medium Heel Sandals",
    img: "/products/product-028.webp",
    description_ar:
      "صندل نسائي بكعب متوسط الارتفاع، مثالي للمناسبات والأمسيات.\nمصمم بأناقة ومتوفر بعدة ألوان.",
    description_en:
      "Women's medium heel sandals, perfect for occasions and evenings.\nDesigned with elegance and available in multiple colors.",
    categories: ["SANDALS", "WOMENS_SHOES"],
    colors: ["BLACK", "SILVER", "GOLD"],
    price: { original: "79.99", sale: null },
    relatedProducts: ["004", "010", "029", "037"],
    rating: 4,
    inStock: 12,
  },
  {
    id: "029",
    name_ar: "صندل نسائي بكعب عالي",
    name_en: "Women's High Heel Sandals",
    img: "/products/product-029.webp",
    description_ar:
      "صندل نسائي بكعب عالي مثالي للمناسبات الصيفية.\nمصنوع من مواد مريحة ومتينة.",
    description_en:
      "Women's high heel sandals perfect for summer occasions.\nMade with comfortable and durable materials.",
    categories: ["SANDALS", "WOMENS_SHOES"],
    colors: ["BLACK", "GOLD", "SILVER"],
    price: { original: "79.99", sale: "59.99" },
    relatedProducts: ["004", "010", "028", "030"],
    rating: 4,
    inStock: 15,
  },
  {
    id: "030",
    name_ar: "حذاء رياضي مريح للرجال",
    name_en: "Men's Comfortable Sports Shoes",
    img: "/products/product-030.webp",
    description_ar:
      "حذاء رياضي مريح وأنيق للرجال، يوفر الدعم والراحة أثناء التمارين الرياضية.\nمصمم بتقنيات حديثة لتحقيق أداء ممتاز.",
    description_en:
      "Comfortable and stylish sports shoes for men, providing support and comfort during workouts.\nDesigned with modern technologies for excellent performance.",
    categories: ["ATHLETIC_SHOES", "MENS_SHOES"],
    colors: ["BLACK", "WHITE", "GREY"],
    price: { original: "89.99", sale: null },
    relatedProducts: ["001", "012", "024", "031"],
    rating: 5,
    inStock: 34,
  },
  {
    id: "031",
    name_ar: "حذاء رياضي مريح للنساء",
    name_en: "Women's Comfortable Sports Shoes",
    img: "/products/product-031.webp",
    description_ar:
      "حذاء رياضي مريح للنساء، يوفر دعمًا ممتازًا للقدمين أثناء التمرينات الرياضية.\nمصنوع من مواد عالية الجودة.",
    description_en:
      "Comfortable sports shoes for women, providing excellent foot support during workouts.\nMade with high-quality materials.",
    categories: ["ATHLETIC_SHOES", "WOMENS_SHOES"],
    colors: ["WHITE", "GREY", "PINK"],
    price: { original: "79.99", sale: null },
    relatedProducts: ["002", "013", "032", "033"],
    rating: 5,
    inStock: 41,
  },
  {
    id: "032",
    name_ar: "حذاء ركض خفيف للنساء",
    name_en: "Women's Lightweight Running Shoes",
    img: "/products/product-032.webp",
    description_ar:
      "حذاء ركض خفيف للنساء، مثالي للركض اليومي والتمارين الرياضية.\nتصميم يوفر دعمًا وراحة طوال اليوم.",
    description_en:
      "Lightweight running shoes for women, perfect for daily running and sports activities.\nDesigned for support and comfort all day long.",
    categories: ["ATHLETIC_SHOES", "WOMENS_SHOES"],
    colors: ["BLUE", "PINK", "BLACK"],
    price: { original: "69.99", sale: null },
    relatedProducts: ["002", "014", "038", "039"],
    rating: 4,
    inStock: 56,
  },
  {
    id: "033",
    name_ar: "حذاء رياضي مريح للنساء",
    name_en: "Women's Comfortable Sports Shoes",
    img: "/products/product-033.webp",
    description_ar:
      "حذاء رياضي مريح للنساء، يوفر دعمًا ممتازًا للقدمين أثناء التمرينات الرياضية.\nمصنوع من مواد عالية الجودة.",
    description_en:
      "Comfortable sports shoes for women, providing excellent foot support during workouts.\nMade with high-quality materials.",
    categories: ["ATHLETIC_SHOES", "WOMENS_SHOES"],
    colors: ["WHITE", "GREY", "PINK"],
    price: { original: "79.99", sale: null },
    relatedProducts: ["002", "013", "031", "034"],
    rating: 5,
    inStock: 41,
  },
  {
    id: "034",
    name_ar: "حذاء ركض خفيف للرجال",
    name_en: "Men's Lightweight Running Shoes",
    img: "/products/product-034.webp",
    description_ar:
      "حذاء ركض خفيف الوزن ومناسب للرجال.\nمصمم لتحقيق السرعة والراحة أثناء الجري.",
    description_en:
      "Lightweight and suitable running shoes for men.\nDesigned for speed and comfort during running.",
    categories: ["ATHLETIC_SHOES", "MENS_SHOES"],
    colors: ["BLACK", "RED", "BLUE"],
    price: { original: "89.99", sale: null },
    relatedProducts: ["001", "012", "016", "035"],
    rating: 4,
    inStock: 22,
  },
  {
    id: "035",
    name_ar: "صندل نسائي مريح بدون كعب",
    name_en: "Women's Comfortable Flat Sandals",
    img: "/products/product-035.webp",
    description_ar:
      "صندل نسائي مريح بدون كعب، مثالي للارتداء اليومي خلال فصل الصيف.\nمتوفر بعدة ألوان.",
    description_en:
      "Comfortable flat sandals for women, perfect for daily wear during the summer season.\nAvailable in multiple colors.",
    categories: ["SANDALS", "WOMENS_SHOES"],
    colors: ["BLACK", "BROWN", "SILVER"],
    price: { original: "44.99", sale: null },
    relatedProducts: ["004", "010", "027", "036"],
    rating: 5,
    inStock: 28,
  },
  {
    id: "036",
    name_ar: "حذاء رياضي مريح للنساء",
    name_en: "Women's Comfortable Sports Shoes",
    img: "/products/product-036.webp",
    description_ar:
      "حذاء رياضي مريح للنساء، يوفر دعمًا ممتازًا للقدمين أثناء التمرينات الرياضية.\nمصنوع من مواد عالية الجودة.",
    description_en:
      "Comfortable sports shoes for women, providing excellent foot support during workouts.\nMade with high-quality materials.",
    categories: ["ATHLETIC_SHOES", "WOMENS_SHOES"],
    colors: ["WHITE", "GREY", "PINK"],
    price: { original: "79.99", sale: null },
    relatedProducts: ["002", "013", "031", "035"],
    rating: 5,
    inStock: 41,
  },
  {
    id: "037",
    name_ar: "صندل نسائي بكعب متوسط",
    name_en: "Women's Medium Heel Sandals",
    img: "/products/product-037.webp",
    description_ar:
      "صندل نسائي بكعب متوسط الارتفاع، مثالي للمناسبات والأمسيات.\nمصمم بأناقة ومتوفر بعدة ألوان.",
    description_en:
      "Women's medium heel sandals, perfect for occasions and evenings.\nDesigned with elegance and available in multiple colors.",
    categories: ["SANDALS", "WOMENS_SHOES"],
    colors: ["BLACK", "SILVER", "GOLD"],
    price: { original: "79.99", sale: null },
    relatedProducts: ["004", "010", "028", "038"],
    rating: 4,
    inStock: 12,
  },
  {
    id: "038",
    name_ar: "حذاء ركض خفيف للنساء",
    name_en: "Women's Lightweight Running Shoes",
    img: "/products/product-038.webp",
    description_ar:
      "حذاء ركض خفيف للنساء، مثالي للركض اليومي والتمارين الرياضية.\nتصميم يوفر دعمًا وراحة طوال اليوم.",
    description_en:
      "Lightweight running shoes for women, perfect for daily running and sports activities.\nDesigned for support and comfort all day long.",
    categories: ["ATHLETIC_SHOES", "WOMENS_SHOES"],
    colors: ["BLUE", "PINK", "BLACK"],
    price: { original: "69.99", sale: null },
    relatedProducts: ["002", "014", "032", "039"],
    rating: 4,
    inStock: 56,
  },
  {
    id: "039",
    name_ar: "حذاء ركض خفيف للنساء",
    name_en: "Women's Lightweight Running Shoes",
    img: "/products/product-039.webp",
    description_ar:
      "حذاء ركض خفيف للنساء، مثالي للركض اليومي والتمارين الرياضية.\nتصميم يوفر دعمًا وراحة طوال اليوم.",
    description_en:
      "Lightweight running shoes for women, perfect for daily running and sports activities.\nDesigned for support and comfort all day long.",
    categories: ["ATHLETIC_SHOES", "WOMENS_SHOES"],
    colors: ["BLUE", "PINK", "BLACK"],
    price: { original: "69.99", sale: null },
    relatedProducts: ["002", "014", "032", "038"],
    rating: 4,
    inStock: 56,
  },
  {
    id: "040",
    name_ar: "أحذية شتوية دافئة للنساء",
    name_en: "Women's Warm Winter Boots",
    img: "/products/product-040.webp",
    description_ar:
      "أحذية شتوية دافئة وأنيقة للنساء.\nمثالية للأيام الباردة والمناسبات الشتوية.",
    description_en:
      "Warm and stylish winter boots for women.\nPerfect for cold days and winter occasions.",
    categories: ["BOOTS", "WOMENS_SHOES"],
    colors: ["BLACK", "BROWN", "GREY"],
    price: { original: "109.99", sale: null },
    relatedProducts: ["002", "005", "041", "042"],
    rating: 5,
    inStock: 7,
  },
  {
    id: "041",
    name_ar: "أحذية شتوية دافئة للرجال",
    name_en: "Men's Warm Winter Boots",
    img: "/products/product-041.webp",
    description_ar:
      "أحذية شتوية دافئة وأنيقة للرجال.\nمثالية للأيام الباردة والمناسبات الشتوية.",
    description_en:
      "Warm and stylish winter boots for men.\nPerfect for cold days and winter occasions.",
    categories: ["BOOTS", "MENS_SHOES"],
    colors: ["BLACK", "BROWN", "GREY"],
    price: { original: "109.99", sale: null },
    relatedProducts: ["001", "007", "040", "042"],
    rating: 5,
    inStock: 8,
  },
  {
    id: "042",
    name_ar: "أحذية شتوية دافئة للنساء",
    name_en: "Women's Warm Winter Boots",
    img: "/products/product-042.webp",
    description_ar:
      "أحذية شتوية دافئة وأنيقة للنساء.\nمثالية للأيام الباردة والمناسبات الشتوية.",
    description_en:
      "Warm and stylish winter boots for women.\nPerfect for cold days and winter occasions.",
    categories: ["BOOTS", "WOMENS_SHOES"],
    colors: ["BLACK", "BROWN", "GREY"],
    price: { original: "109.99", sale: null },
    relatedProducts: ["002", "005", "040", "041"],
    rating: 5,
    inStock: 5,
  },
  {
    id: "043",
    name_ar: "حقيبة ظهر للرجال",
    name_en: "Men's Backpack",
    img: "/products/product-043.webp",
    description_ar:
      "حقيبة ظهر عملية وأنيقة للرجال.\nمثالية للإستخدام اليومي والسفر.",
    description_en:
      "Practical and stylish backpack for men.\nIdeal for daily use and travel.",
    categories: ["MENS_ACCESSORIES"],
    colors: ["BLACK", "GREY"],
    price: { original: "49.99", sale: null },
    relatedProducts: ["003", "044", "045", "046"],
    rating: 4,
    inStock: 30,
  },
  {
    id: "044",
    name_ar: "حقيبة ظهر للنساء",
    name_en: "Women's Backpack",
    img: "/products/product-044.webp",
    description_ar:
      "حقيبة ظهر عملية وأنيقة للنساء.\nمثالية للإستخدام اليومي والسفر.",
    description_en:
      "Practical and stylish backpack for women.\nIdeal for daily use and travel.",
    categories: ["WOMENS_ACCESSORIES"],
    colors: ["BLACK", "PINK"],
    price: { original: "44.99", sale: null },
    relatedProducts: ["004", "043", "045", "047"],
    rating: 4,
    inStock: 25,
  },
  {
    id: "045",
    name_ar: "حقيبة ظهر للأطفال",
    name_en: "Kids' Backpack",
    img: "/products/product-045.webp",
    description_ar:
      "حقيبة ظهر عملية ومريحة للأطفال.\nمثالية للإستخدام اليومي والمدرسة.",
    description_en:
      "Practical and comfortable backpack for kids.\nIdeal for daily use and school.",
    categories: ["KIDS_ACCESSORIES"],
    colors: ["BLUE", "PINK"],
    price: { original: "29.99", sale: null },
    relatedProducts: ["005", "043", "044", "046"],
    rating: 4,
    inStock: 15,
  },
  {
    id: "046",
    name_ar: "حقيبة ظهر للأطفال",
    name_en: "Kids' Backpack",
    img: "/products/product-046.webp",
    description_ar:
      "حقيبة ظهر عملية ومريحة للأطفال.\nمثالية للإستخدام اليومي والمدرسة.",
    description_en:
      "Practical and comfortable backpack for kids.\nIdeal for daily use and school.",
    categories: ["KIDS_ACCESSORIES"],
    colors: ["BLUE", "RED"],
    price: { original: "29.99", sale: null },
    relatedProducts: ["005", "043", "044", "045"],
    rating: 4,
    inStock: 20,
  },
  {
    id: "047",
    name_ar: "حقيبة ظهر للنساء",
    name_en: "Women's Backpack",
    img: "/products/product-047.webp",
    description_ar:
      "حقيبة ظهر عملية وأنيقة للنساء.\nمثالية للإستخدام اليومي والسفر.",
    description_en:
      "Practical and stylish backpack for women.\nIdeal for daily use and travel.",
    categories: ["WOMENS_ACCESSORIES"],
    colors: ["BLACK", "BROWN"],
    price: { original: "44.99", sale: null },
    relatedProducts: ["004", "043", "044", "048"],
    rating: 4,
    inStock: 22,
  },
  {
    id: "048",
    name_ar: "حقيبة ظهر للرجال",
    name_en: "Men's Backpack",
    img: "/products/product-048.webp",
    description_ar:
      "حقيبة ظهر عملية وأنيقة للرجال.\nمثالية للإستخدام اليومي والسفر.",
    description_en:
      "Practical and stylish backpack for men.\nIdeal for daily use and travel.",
    categories: ["MENS_ACCESSORIES"],
    colors: ["BLACK", "GREY"],
    price: { original: "49.99", sale: null },
    relatedProducts: ["003", "043", "044", "047"],
    rating: 4,
    inStock: 28,
  },
  {
    id: "049",
    name_ar: "حذاء رياضي مريح للرجال",
    name_en: "Men's Comfortable Sports Shoes",
    img: "/products/product-049.webp",
    description_ar:
      "حذاء رياضي مريح وأنيق للرجال، يوفر الدعم والراحة أثناء التمارين الرياضية.\nمصمم بتقنيات حديثة لتحقيق أداء ممتاز.",
    description_en:
      "Comfortable and stylish sports shoes for men, providing support and comfort during workouts.\nDesigned with modern technologies for excellent performance.",
    categories: ["ATHLETIC_SHOES", "MENS_SHOES"],
    colors: ["BLACK", "WHITE", "GREY"],
    price: { original: "89.99", sale: null },
    relatedProducts: ["001", "012", "024", "050"],
    rating: 5,
    inStock: 34,
  },
  {
    id: "050",
    name_ar: "حذاء رياضي مريح للنساء",
    name_en: "Women's Comfortable Sports Shoes",
    img: "/products/product-050.webp",
    description_ar:
      "حذاء رياضي مريح للنساء، يوفر دعمًا ممتازًا للقدمين أثناء التمرينات الرياضية.\nمصنوع من مواد عالية الجودة.",
    description_en:
      "Comfortable sports shoes for women, providing excellent foot support during workouts.\nMade with high-quality materials.",
    categories: ["ATHLETIC_SHOES", "WOMENS_SHOES"],
    colors: ["WHITE", "GREY", "PINK"],
    price: { original: "79.99", sale: null },
    relatedProducts: ["002", "013", "031", "033"],
    rating: 5,
    inStock: 41,
  },
];
